#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow OpenSSH
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo systemctl restart nginx
