#!/usr/bin/env bash
# Configure server with: HAproxy version 2
# Distributes request using roundrobin; sends traffic to servers: web-01 and web-02

CFG="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 326986-web-01 100.26.156.173 check\n\tserver 326986-web-02 54.157.184.250 check\n"

sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get install -y haproxy=2.0\*

sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

sudo sed -i "\$a $CFG" /etc/haproxy/haproxy.cfg

sudo service haproxy start
