#!/usr/bin/env bash
# Configure web-01 so that its firewall
# redirects port 8080/TCP to port 80/TCP.
sudo apt update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo iptables-save > /etc/iptables/rules.v4
sudo ufw enable
